# check-command-parity.ps1
# Verifies the 4 unified command contracts stay aligned across Claude, Junie, and Windsurf.

$ErrorActionPreference = 'Stop'

$RepoDir = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Definition)

# Note: .claude/skills/ files are GENERATED by sync-claude.ps1 from templates
# They are NOT source files in this repo. We skip checking them as they may not exist.
# Source of truth for unified commands: .junie/commands/ and .windsurf/workflows/

$checks = @(
    @{
        Name = 'review'
        Junie = '.junie/commands/review.md'
        Windsurf = '.windsurf/workflows/review.md'
        Patterns = @(
            '\[Critical\] \| \[Warning\] \| \[Suggestion\]'
        )
    },
    @{
        Name = 'plan'
        Junie = '.junie/commands/plan.md'
        Windsurf = '.windsurf/workflows/plan.md'
        Patterns = @(
            'Risk'
        )
    },
    @{
        Name = 'test-generate'
        Junie = '.junie/commands/test-generate.md'
        Windsurf = '.windsurf/workflows/test-generate.md'
        Patterns = @(
            'pytest'
        )
    },
    @{
        Name = 'git-commit'
        Junie = '.junie/commands/git-commit.md'
        Windsurf = '.windsurf/workflows/git-commit.md'
        Patterns = @(
            'run `git commit`',
            'created commit hash and final commit message'
        )
    }
)

$failures = New-Object System.Collections.Generic.List[string]

foreach ($check in $checks) {
    $paths = @($check.Junie, $check.Windsurf)
    foreach ($relativePath in $paths) {
        $fullPath = Join-Path $RepoDir $relativePath
        if (-not (Test-Path $fullPath)) {
            $failures.Add("Missing file: $relativePath")
            continue
        }

        $content = Get-Content -Raw -Path $fullPath
        foreach ($pattern in $check.Patterns) {
            if ($content -notmatch $pattern) {
                $failures.Add("[$($check.Name)] pattern '$pattern' not found in $relativePath")
            }
        }
    }
}

# Check ALL Junie commands for unsupported frontmatter (unified + speckit)
$junieCommandsDir = Join-Path $RepoDir '.junie/commands'
if (Test-Path $junieCommandsDir) {
    $junieCommandPaths = Get-ChildItem -Path $junieCommandsDir -Filter '*.md' | Select-Object -ExpandProperty FullName
    foreach ($path in $junieCommandPaths) {
        $content = Get-Content -Raw -Path $path
        if ($content -match '(?m)^name:') {
            $failures.Add("Junie command uses unsupported 'name' frontmatter: $([System.IO.Path]::GetRelativePath($RepoDir, $path))")
        }
        if ($content -match '(?m)^arguments:') {
            $failures.Add("Junie command uses unsupported 'arguments' frontmatter: $([System.IO.Path]::GetRelativePath($RepoDir, $path))")
        }
    }
}

if ($failures.Count -gt 0) {
    Write-Host 'Command parity check failed:' -ForegroundColor Red
    foreach ($failure in $failures) {
        Write-Host "- $failure"
    }
    exit 1
}

Write-Host 'Command parity check passed.' -ForegroundColor Green